#!/bin/bash
# My shellscript
echo "The Project for Ktrace execution time " > ktraceoutput.txt
echo "The Project for Counter " >> ktraceoutput.txt
for i in 1 2 3 4 5 6 7 8 9 10
do
echo "$i times" >> ktraceoutput.txt
ktrace -t c -d ../../NetBeansProjects/c/main  >>ktraceoutput.txt
done
echo "The Project for dup and exit base " >> ktraceoutput.txt
for j in 1 2 3 4 5 6 7 8 9 10
do
echo "$j times" >>ktraceoutput.txt
ktrace -t c -d ../../NetBeansProjects/d/main  >>ktraceoutput.txt
done
echo "The Project for I/O " >> ktraceoutput.txt
for k in 1 2 3 4 5 6 7 8 9 10
do
echo "$k times" >>ktraceoutput.txt
ktrace -t c -d ../../NetBeansProjects/i/main  >>ktraceoutput.txt
done
echo "The Project for sysbench " >> ktraceoutput.txt
for l in 1 2 3 4 5 6 7 8 9 10
do
echo "$l times" >>ktraceoutput.txt
ktrace -t c -d sysbench --test=cpu --cpu-max-prime=20000 run  >>ktraceoutput.txt
done

echo "That's It!" >>ktraceoutput.txt
