#!/bin/bash
# My shellscript
echo "The Project for pure execution time " > pureoutput.txt
echo "The Project for Counter " >> pureoutput.txt
for i in 1 2 3 4 5 6 7 8 9 10
do
echo "$i times" >> pureoutput.txt
../../NetBeansProjects/c/main >>pureoutput.txt
done
echo "The Project for dup and exit base " >> pureoutput.txt
for j in 1 2 3 4 5 6 7 8 9 10
do
echo "$j times" >>pureoutput.txt
../../NetBeansProjects/d/main >>pureoutput.txt
done
echo "The Project for I/O " >> pureoutput.txt
for k in 1 2 3 4 5 6 7 8 9 10
do
echo "$k times" >>pureoutput.txt
../../NetBeansProjects/i/main  >>pureoutput.txt
done
echo "The Project for sysbench " >> pureoutput.txt
for l in 1 2 3 4 5 6 7 8 9 10
do
echo "$l times" >>pureoutput.txt
sysbench --test=cpu --cpu-max-prime=20000 run >>pureoutput.txt
done

echo "That's It!" >>pureoutput.txt
